spring:
    profiles:
      active: postgres
    datasource:
      url: jdbc:postgresql://localhost:5432/manageliquibase?currentSchema=dating
      username: postgres
      password: admin
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql
      openInView: false
      show_sql: true
      generate-ddl: false
      hibernate:
        ddl-auto: none
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate.cache.use_query_cache: false
          hibernate.generate_statistics: true
        sql:
          init:
            platform: postgres
            schema-locations: classpath:init-schema.sql
            mode: always
    main:
      log-startup-info: false


#spring:
#    profiles:
#      active: h2
#    datasource:
#      url: jdbc:h2:mem:dating;DB_CLOSE_DELAY=-1
#      username: sa
#      password: password
#    h2:
#      console:
#        enabled: true
#        path: /h2-console
#    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
#      database: H2
#      openInView: false
#      show_sql: true
#      generate-ddl: false
#      hibernate:
#        ddl-auto: none
#        naming:
#            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      properties:
#          hibernate:
#              cache:
#                  use_query_cache: false
#              generate_statistics: true
#    main:
#        log-startup-info: false
#    liquibase:
#      change-log: classpath:db-with-sample-data.xml